In [1]:
import pandas as pd
import numpy as np
import datetime as dt
import warnings
from functions import *

pd.set_option('display.max_columns', None) # display all columns
warnings.filterwarnings('ignore') # ignore warnings

pd.set_option('display.max_colwidth', None)

In [63]:
#Cargamos los CSV y comprobamos
data_balance = pd.read_csv("balance_sheet_since_2018.csv")
data_cash_flow = pd.read_csv("cash_flow_since_2018.csv")
data_company_overview = pd.read_csv("company_overview.csv")
data_income_statement = pd.read_csv("income_statement_since_2018.csv")

In [64]:
balance_df = data_balance.copy()
cf_df = data_cash_flow.copy()
overview_df = data_company_overview.copy()
income_df = data_income_statement.copy()

In [ ]:
def date2col(df, col):
    df[col] = pd.to_datetime(df[col])
    df['year'] = df[col].dt.year

In [68]:
date2col(balance_df, 'fiscalDateEnding')
date2col(cf_df, 'fiscalDateEnding')
date2col(income_df, 'fiscalDateEnding')

In [79]:
balance_df[(balance_df['year'] >= 2018) & (balance_df['year'] < 2024)].reset_index(drop=True)

,fiscalDateEnding,reportedCurrency,totalAssets,totalCurrentAssets,cashAndCashEquivalentsAtCarryingValue,cashAndShortTermInvestments,inventory,currentNetReceivables,totalNonCurrentAssets,propertyPlantEquipment,accumulatedDepreciationAmortizationPPE,intangibleAssets,intangibleAssetsExcludingGoodwill,goodwill,investments,longTermInvestments,shortTermInvestments,otherCurrentAssets,otherNonCurrentAssets,totalLiabilities,totalCurrentLiabilities,currentAccountsPayable,deferredRevenue,currentDebt,shortTermDebt,totalNonCurrentLiabilities,capitalLeaseObligations,longTermDebt,currentLongTermDebt,longTermDebtNoncurrent,shortLongTermDebtTotal,otherCurrentLiabilities,otherNonCurrentLiabilities,totalShareholderEquity,treasuryStock,retainedEarnings,commonStock,commonStockSharesOutstanding,symbol,sector,year
0,2023-12-31,USD,264811000000,2.398700e+10,6.215000e+09,6.525000e+09,NaN,1.381300e+10,2.721390e+11,5.968600e+10,5.870100e+10,1.830350e+11,1.237670e+11,5.926800e+10,9.694000e+09,9.385000e+09,3.100000e+08,3.959000e+09,1.233300e+10,1.821080e+11,4.019800e+10,1.243700e+10,3.860000e+09,2.069000e+09,2.069000e+09,1.476020e+11,NaN,1.032000e+11,2.069000e+09,9.220000e+10,1.032000e+11,2.245000e+10,2.012200e+10,8.270300e+10,7.517000e+09,5.289200e+10,48000000.0,4.008000e+09,CMCSA,Comunicacion,2023
1,2022-12-31,USD,257275000000,2.182600e+10,4.749000e+09,5.151000e+09,NaN,1.267200e+10,2.765450e+11,5.548500e+10,5.690000e+10,1.934020e+11,1.349080e+11,5.849400e+10,8.142000e+09,7.740000e+09,4.020000e+08,4.406000e+09,1.249700e+10,1.763320e+11,2.788700e+10,1.254400e+10,3.115000e+09,1.743000e+09,1.743000e+09,1.490190e+11,NaN,1.009000e+11,1.743000e+09,8.690000e+10,1.009000e+11,1.122000e+10,2.039500e+10,8.094300e+10,7.517000e+09,5.160900e+10,51000000.0,4.277000e+09,CMCSA,Comunicacion,2022
2,2021-12-31,USD,275905000000,2.480700e+10,8.711000e+09,9.079000e+09,NaN,1.200800e+10,2.981680e+11,5.400000e+10,5.560000e+10,2.155040e+11,1.453150e+11,7.020000e+10,9.055000e+09,8.082000e+09,3.680000e+08,4.088000e+09,1.242400e+10,1.798130e+11,2.934800e+10,1.245500e+10,3.735000e+09,2.132000e+09,2.132000e+09,1.505470e+11,NaN,1.114320e+11,2.132000e+09,1.093000e+11,1.008020e+11,1.172100e+10,2.062000e+10,9.609200e+10,7.517000e+09,6.190200e+10,54000000.0,4.557000e+09,CMCSA,Comunicacion,2021
3,2020-12-31,USD,273869000000,2.674100e+10,1.174000e+10,1.203200e+10,NaN,1.146600e+10,2.909530e+11,5.199500e+10,5.438800e+10,2.181460e+11,1.474770e+11,7.070000e+10,8.559000e+09,7.820000e+09,2.920000e+08,3.535000e+09,8.103000e+09,1.835460e+11,2.879600e+10,1.136400e+10,3.713000e+09,3.146000e+09,3.146000e+09,1.513770e+11,NaN,1.287460e+11,3.146000e+09,1.256000e+11,1.054090e+11,1.132300e+10,1.822200e+10,9.032300e+10,7.517000e+09,5.643800e+10,54000000.0,4.583000e+09,CMCSA,Comunicacion,2020
4,2019-12-31,USD,263414000000,2.539200e+10,5.500000e+09,7.209000e+09,3.877000e+09,1.129200e+10,2.815320e+11,4.832200e+10,5.323900e+10,2.159710e+11,1.472460e+11,6.872500e+10,9.392000e+09,6.989000e+09,1.709000e+09,4.723000e+09,8.866000e+09,1.806880e+11,3.029200e+10,1.082600e+10,3.386000e+09,4.452000e+09,4.452000e+09,1.443280e+11,NaN,1.038900e+11,4.452000e+09,1.158000e+11,1.038900e+11,1.224600e+10,1.676500e+10,8.272600e+10,7.517000e+09,5.069500e+10,54000000.0,4.560000e+09,CMCSA,Comunicacion,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,2022-12-31,USD,185727000000,5.954900e+10,1.468100e+10,4.076300e+10,NaN,1.346600e+10,4.047600e+10,7.951800e+10,NaN,2.120300e+10,8.970000e+08,2.030600e+10,5.210600e+10,1.700000e+07,2.608200e+10,5.345000e+09,6.583000e+09,6.001400e+10,2.702600e+10,6.107000e+09,1.008000e+09,1.290000e+08,1.000000e+10,4.019100e+10,558000000.0,9.923000e+09,NaN,9.923000e+09,1.992300e+10,4.906000e+09,7.764000e+09,1.257130e+11,NaN,6.479900e+10,0.0,2.639000e+09,META,Tecnologia de la Informacion,2022
326,2021-12-31,USD,165987000000,6.666600e+10,1.660100e+10,4.799800e+10,NaN,1.403900e+10,3.477100e+10,5.780900e+10,NaN,1.983100e+10,6.340000e+08,1.919700e+10,6.282800e+10,3.400000e+07,3.139700e+10,4.629000e+09,2.751000e+09,4.110800e+10,2.113500e+10,5.135000e+09,1.113000e+09,7.500000e+07,1.127000e+09,2.641700e+10,506000000.0,NaN,NaN,0.000000e+00,1.387300e+10,1.536400e+10,7.227000e+09,1.248790e+11,NaN,6.976100e+10,0.0,2.764000e+09,META,Tecnologia de la Informacion,2021
327,2020-12-31,USD,159316000000,7.567000e+10,1.757600e+10,6.195400e+10,NaN,1.133500e+10,3.177900e+10,4.563300e+10,NaN,1.967300e+10,6.230000e+08,1.905000e+10,8.875600e+10,6.200000e+07,4.437800e+10,2.381000e+09,2.758000e+09,3.102600e+10,1.498100e+10,1.331000e+09,7.170000e+08,5.400000e+07,1.023000e+09,2.153900e+10,469000000.0,NaN,NaN,NaN,1.065400e+10,1.224500e+10,6.414000e+09,1.282900e+11,NaN,7.734500e+10,0.0,2.854000e+09,META,Tecnologia de la Informacion,2020
328,2019-12-31,USD,133376000000,6.622500e+10,1.907900e+10,5.485500e+10,NaN,9.518000e+09,3.182800e+10,3.532300e+10,1.066300e+10,1.960900e+10,8.940000e+08,1.871500e+10,7.155200e+10,NaN,3.577600e+10,1.852000e+09,2.673000e+09,3.232200e+10,1.505300e+10,1.363000e+09,5.030000e+08,8.550000e+08,8.000000e+08,1.830800e+10,418000000.0,NaN,8.000000e+08,NaN,1.032400e+10,1.262100e+10,7.745000e+09,1.010540e+11,NaN,5.569200e+10,0.0,2.851000e+09,META,Tecnologia de la Informacion,2019
329,2018-12-31,USD,97334000000,5.048000e+10,1.001900e+10,4.111400e+10,NaN,7.587000e+09,4.685400e+10,2.468300e+10,6.890000e+09,1.959500e+10,1.294000e+09,1.830100e+10,6.219000e+10,NaN,3.109500e+10,1.779000e+09,2.576000e+09,1.320700e+10,7.017000e+09,8.200000e+08,2.640000e+08,NaN,5.000000e+08,6.190000e+09,418000000.0,NaN,5.000000e+08,NaN,5.000000e+08,5.550000e+09,6.190000e+09,8.412700e+10,NaN,4.198100e+10,0.0,2.875000e+09,META,Tecnologia de la Informacion,2018

In [80]:
balance_df = balance_df[(balance_df['year'] >= 2018) & (balance_df['year'] < 2024)].reset_index(drop=True)
cf_df = cf_df[(cf_df['year'] >= 2018) & (cf_df['year'] < 2024)].reset_index(drop=True)
income_df = income_df[(income_df['year'] >= 2018) & (income_df['year'] < 2024)].reset_index(drop=True)

In [129]:
explore_data(overview_df)

There are 0 duplicate rows. Also;

                            NaN  NaN %  EmptySpaces
Symbol                        0    0.0            0
AssetType                     0    0.0            0
Name                          0    0.0            0
Description                   0    0.0            0
CIK                           0    0.0            0
Exchange                      0    0.0            0
Currency                      0    0.0            0
Country                       0    0.0            0
Industry                      0    0.0            0
Address                       0    0.0            0
OfficialSite                  0    0.0            0
FiscalYearEnd                 0    0.0            0
LatestQuarter                 0    0.0            0
MarketCapitalization          0    0.0            0
PEGRatio                      0    0.0            0
BookValue                     0    0.0            0
DividendPerShare              0    0.0            0
DividendYield                 0    0.0            0
EPS                           0    0.0            0
RevenuePerShareTTM            0    0.0            0
ProfitMargin                  0    0.0            0
OperatingMarginTTM            0    0.0            0
ReturnOnAssetsTTM             0    0.0            0
ReturnOnEquityTTM             0    0.0            0
RevenueTTM                    0    0.0            0
GrossProfitTTM                0    0.0            0
DilutedEPSTTM                 0    0.0            0
QuarterlyEarningsGrowthYOY    0    0.0            0
QuarterlyRevenueGrowthYOY     0    0.0            0
AnalystTargetPrice            0    0.0            0
AnalystRatingStrongBuy        0    0.0            0
AnalystRatingBuy              0    0.0            0
AnalystRatingHold             0    0.0            0
AnalystRatingSell             0    0.0            0
AnalystRatingStrongSell       0    0.0            0
ForwardPE                     0    0.0            0
PriceToSalesRatioTTM          0    0.0            0
EVToRevenue                   0    0.0            0
Beta                          0    0.0            0
52WeekHigh                    0    0.0            0
52WeekLow                     0    0.0            0
50DayMovingAverage            0    0.0            0
200DayMovingAverage           0    0.0            0
SharesOutstanding             0    0.0            0
sector                        0    0.0            0

In [ ]:
overview_df.drop(columns=['Sector','EBITDA','PERatio','DividendDate','ExDividendDate','TrailingPE','PriceToBookRatio','EVToEBITDA','AssetType','Currency','Country','fiscal_year_end', 'latest_quarter', 'market_capitalization', 'pegratio', 'book_value', 'dividend_per_share',
 'dividend_yield',  'eps', 'revenue_per_share_ttm', 'profit_margin', 'operating_margin_ttm', 'return_on_assets_ttm', 'return_on_equity_ttm',
 'revenue_ttm', 'gross_profit_ttm', 'diluted_epsttm', 'quarterly_earnings_growth_yoy', 'quarterly_revenue_growth_yoy', 'analyst_target_price',
 'analyst_rating_strong_buy', 'analyst_rating_buy', 'analyst_rating_hold', 'analyst_rating_sell', 'analyst_rating_strong_sell', 'forward_pe',
 'price_to_sales_ratio_ttm', 'evto_revenue', 'beta', '52week_high', '52week_low', '50day_moving_average', '200day_moving_average', 'shares_outstanding'], inplace=True)

In [103]:
overview_df[['DividendPerShare', 'DividendYield']] = overview_df[['DividendPerShare', 'DividendYield']].fillna(0)

In [118]:
overview_df['LatestQuarter'] = pd.to_datetime(overview_df['LatestQuarter'])

In [134]:
open_data(overview_df)

Data shape is (55, 45).

Symbol                                object
AssetType                             object
Name                                  object
Description                           object
CIK                                    int64
Exchange                              object
Currency                              object
Country                               object
Industry                              object
Address                               object
OfficialSite                          object
FiscalYearEnd                         object
LatestQuarter                 datetime64[ns]
MarketCapitalization                   int64
PEGRatio                             float64
BookValue                            float64
DividendPerShare                     float64
DividendYield                        float64
EPS                                  float64
RevenuePerShareTTM                   float64
ProfitMargin                         float64
OperatingMarginTTM                   float64
ReturnOnAssetsTTM                    float64
ReturnOnEquityTTM                    float64
RevenueTTM                             int64
GrossProfitTTM                         int64
DilutedEPSTTM                        float64
QuarterlyEarningsGrowthYOY           float64
QuarterlyRevenueGrowthYOY            float64
AnalystTargetPrice                   float64
AnalystRatingStrongBuy                 int64
AnalystRatingBuy                       int64
AnalystRatingHold                      int64
AnalystRatingSell                      int64
AnalystRatingStrongSell                int64
ForwardPE                            float64
PriceToSalesRatioTTM                 float64
EVToRevenue                          float64
Beta                                 float64
52WeekHigh                           float64
52WeekLow                            float64
50DayMovingAverage                   float64
200DayMovingAverage                  float64
SharesOutstanding                      int64
sector                                object
dtype: object

Data row sample and full columns:

,Symbol,AssetType,Name,Description,CIK,Exchange,Currency,Country,Industry,Address,OfficialSite,FiscalYearEnd,LatestQuarter,MarketCapitalization,PEGRatio,BookValue,DividendPerShare,DividendYield,EPS,RevenuePerShareTTM,ProfitMargin,OperatingMarginTTM,ReturnOnAssetsTTM,ReturnOnEquityTTM,RevenueTTM,GrossProfitTTM,DilutedEPSTTM,QuarterlyEarningsGrowthYOY,QuarterlyRevenueGrowthYOY,AnalystTargetPrice,AnalystRatingStrongBuy,AnalystRatingBuy,AnalystRatingHold,AnalystRatingSell,AnalystRatingStrongSell,ForwardPE,PriceToSalesRatioTTM,EVToRevenue,Beta,52WeekHigh,52WeekLow,50DayMovingAverage,200DayMovingAverage,SharesOutstanding,sector
40,UNH,Common Stock,UnitedHealth Group Incorporated,"UnitedHealth Group Incorporated is an American for-profit multinational managed healthcare and insurance company based in Minnetonka, Minnesota. It offers health care products and insurance services. In 2020, it was the second-largest healthcare company (behind CVS Health) by revenue with $257.1 billion, and the largest insurance company by net premiums. UnitedHealthcare revenues comprise 80% of the Group's overall revenue.",731766,NYSE,USD,USA,HOSPITAL & MEDICAL SERVICE PLANS,"UNITEDHEALTH GROUP CENTER, 9900 BREN ROAD EAST, MINNEAPOLIS, MN, US",https://www.unitedhealthgroup.com,December,2024-09-30,560011280000,1.656,102.42,7.96,0.0138,15.40,427.22,0.0364,0.0864,0.0692,0.1520,393898000000,79617000000,15.40,0.043,0.092,628.08,5,19,4,0,0,20.45,1.422,1.548,0.591,630.73,433.00,584.72,535.91,920284000,Salud
2,DIS,Common Stock,Walt Disney Company,"The Walt Disney Company, commonly known as Disney, is an American diversified multinational mass media and entertainment conglomerate headquartered at the Walt Disney Studios complex in Burbank, California.",1744489,NYSE,USD,USA,SERVICES-MISCELLANEOUS AMUSEMENT & RECREATION,"500 SOUTH BUENA VISTA STREET, BURBANK, CA, US",https://www.thewaltdisneycompany.com,September,2024-09-30,212169736000,1.034,55.41,0.00,0.0082,2.72,49.21,0.0530,0.1490,0.0362,0.0546,90027999000,29697000000,2.72,0.486,0.037,121.67,8,14,9,1,0,21.83,2.357,2.796,1.398,123.17,83.91,99.97,101.97,1810940000,Comunicacion
32,CCI,Common Stock,Crown Castle,"Crown Castle is a real estate investment trust and provider of shared communications infrastructure in the United States. Its network includes over 40,000 cell towers and nearly 80,000 route miles of fiber supporting small cells and fiber solutions. Headquartered in Houston, Texas, the company has 100 offices nationwide.",1051470,NYSE,USD,USA,REAL ESTATE INVESTMENT TRUSTS,"1220 AUGUSTA DRIVE, SUITE 600, HOUSTON, TX, US",https://www.crowncastle.com,December,2024-09-30,45771862000,4.890,12.18,6.26,0.0589,2.82,15.19,0.1860,0.3670,0.0375,0.2050,6593000000,4918000000,2.82,0.142,-0.009,117.71,2,3,13,1,0,37.88,6.970,11.470,0.875,120.92,89.83,109.65,105.77,434598000,Inmobiliario
29,CAT,Common Stock,Caterpillar Inc,"Caterpillar Inc. (often shortened to CAT) is an American Fortune 100 corporation that designs, develops, engineers, manufactures, markets, and sells machinery, engines, financial products, and insurance to customers via a worldwide dealer network.",18230,NYSE,USD,USA,CONSTRUCTION MACHINERY & EQUIP,"510 LAKE COOK ROAD, SUITE 100, DEERFIELD, IL, US",https://www.caterpillar.com,December,2024-09-30,194332639000,2.768,40.18,5.42,0.0140,21.53,133.30,0.1630,0.1950,0.0993,0.5350,65664000000,15565000000,21.53,-0.072,-0.042,379.04,3,7,11,5,0,18.69,2.959,3.477,1.095,418.50,251.54,390.66,354.98,482802000,Industriales
39,NEM,Common Stock,Newmont Goldcorp Corp,"Newmont Corporation, based in Greenwood Village, Colorado, United States, is one of the largest gold mining companies in the world.",1164727,NYSE,USD,USA,GOLD AND SILVER ORES,"6363 SOUTH FIDDLERS GREEN CIRCLE, GREENWOOD VILLAGE, CO, US",https://www.newmont.com,December,2024-09-30,46684852000,0.787,25.97,1.00,0.0238,-2.19,15.33,-0.0714,0.2820,0.0413,-0.0516,16987000000,4526000000,-2.19,3.039,0.847,56.26,2,8,9,0,0,7.36,2.748,3.166,0.531,58.37,28.70,49.34,44.19,1138450000,Materiales

In [143]:
overview_df.columns = overview_df.columns.str.replace('(?<=[a-z])(?=[A-Z])', '_', regex=True).str.lower()

In [145]:
overview_df.reset_index(inplace=True)
overview_df.rename(columns={"index": "company_id"}, inplace=True)

In [146]:
overview_df['state'] = overview_df['address'].apply(lambda x: x.split(',')[-2])

In [211]:
overview_df.to_csv('1_overview.csv', index=False)

In [220]:
# Crear el diccionario para mapear los símbolos a los IDs
symbol_to_id_map = dict(zip(overview_df['symbol'], overview_df['company_id']))
symbol_to_id_map

{'CMCSA': 0,
 'NFLX': 1,
 'DIS': 2,
 'WBD': 3,
 'CHTR': 4,
 'PG': 5,
 'KO': 6,
 'PEP': 7,
 'WMT': 8,
 'COST': 9,
 'AMZN': 10,
 'TSLA': 11,
 'HD': 12,
 'MCD': 13,
 'NKE': 14,
 'XOM': 15,
 'CVX': 16,
 'COP': 17,
 'SLB': 18,
 'EOG': 19,
 'BRK-B': 20,
 'JPM': 21,
 'BAC': 22,
 'WFC': 23,
 'MS': 24,
 'RTX': 25,
 'HON': 26,
 'BA': 27,
 'GE': 28,
 'CAT': 29,
 'PLD': 30,
 'AMT': 31,
 'CCI': 32,
 'SPG': 33,
 'EQR': 34,
 'LIN': 35,
 'SHW': 36,
 'FCX': 37,
 'APD': 38,
 'NEM': 39,
 'UNH': 40,
 'JNJ': 41,
 'LLY': 42,
 'MRK': 43,
 'PFE': 44,
 'NEE': 45,
 'DUK': 46,
 'SO': 47,
 'AEP': 48,
 'EXC': 49,
 'AAPL': 50,
 'MSFT': 51,
 'NVDA': 52,
 'GOOGL': 53,
 'META': 54}

In [221]:
# Crear el diccionario para mapear los símbolos a los IDs
symbol_to_name_map = dict(zip(overview_df['symbol'], overview_df['name']))
symbol_to_name_map

{'CMCSA': 'Comcast Corp',
 'NFLX': 'Netflix Inc',
 'DIS': 'Walt Disney Company',
 'WBD': 'Warner Bros Discovery Inc',
 'CHTR': 'Charter Communications Inc',
 'PG': 'Procter & Gamble Company',
 'KO': 'The Coca-Cola Company',
 'PEP': 'PepsiCo Inc',
 'WMT': 'Walmart Inc',
 'COST': 'Costco Wholesale Corp',
 'AMZN': 'Amazon.com Inc',
 'TSLA': 'Tesla Inc',
 'HD': 'Home Depot Inc',
 'MCD': 'McDonald’s Corporation',
 'NKE': 'Nike Inc',
 'XOM': 'Exxon Mobil Corp',
 'CVX': 'Chevron Corp',
 'COP': 'ConocoPhillips',
 'SLB': 'Schlumberger NV',
 'EOG': 'EOG Resources Inc',
 'BRK-B': 'Berkshire Hathaway Inc',
 'JPM': 'JPMorgan Chase & Co',
 'BAC': 'Bank of America Corp',
 'WFC': 'Wells Fargo & Company',
 'MS': 'Morgan Stanley',
 'RTX': 'Raytheon Technologies Corp',
 'HON': 'Honeywell International Inc',
 'BA': 'The Boeing Company',
 'GE': 'GE Aerospace',
 'CAT': 'Caterpillar Inc',
 'PLD': 'Prologis Inc',
 'AMT': 'American Tower Corp',
 'CCI': 'Crown Castle',
 'SPG': 'Simon Property Group Inc',
 'EQR': 'Equity Residential',
 'LIN': 'Linde plc Ordinary Shares',
 'SHW': 'Sherwin-Williams Co',
 'FCX': 'Freeport-McMoran Copper & Gold Inc',
 'APD': 'Air Products and Chemicals Inc',
 'NEM': 'Newmont Goldcorp Corp',
 'UNH': 'UnitedHealth Group Incorporated',
 'JNJ': 'Johnson & Johnson',
 'LLY': 'Eli Lilly and Company',
 'MRK': 'Merck & Company Inc',
 'PFE': 'Pfizer Inc',
 'NEE': 'Nextera Energy Inc',
 'DUK': 'Duke Energy Corporation',
 'SO': 'Southern Company',
 'AEP': 'American Electric Power Co Inc',
 'EXC': 'Exelon Corporation',
 'AAPL': 'Apple Inc',
 'MSFT': 'Microsoft Corporation',
 'NVDA': 'NVIDIA Corporation',
 'GOOGL': 'Alphabet Inc Class A',
 'META': 'Meta Platforms Inc.'}

In [163]:
balance_df = data_balance.copy()

In [164]:
explore_data(balance_df)

There are 0 duplicate rows. Also;

                                        NaN  NaN %  EmptySpaces
fiscalDateEnding                          0   0.00            0
reportedCurrency                          0   0.00            0
totalAssets                               0   0.00            0
totalCurrentAssets                        0   0.00            0
cashAndCashEquivalentsAtCarryingValue     0   0.00            0
cashAndShortTermInvestments               0   0.00            0
inventory                                32   9.41            0
currentNetReceivables                    48  14.12            0
totalNonCurrentAssets                     0   0.00            0
propertyPlantEquipment                    2   0.59            0
accumulatedDepreciationAmortizationPPE   91  26.76            0
intangibleAssets                         26   7.65            0
intangibleAssetsExcludingGoodwill        48  14.12            0
goodwill                                 42  12.35            0
investments                              51  15.00            0
longTermInvestments                      75  22.06            0
shortTermInvestments                     67  19.71            0
otherCurrentAssets                        0   0.00            0
otherNonCurrentAssets                    62  18.24            0
totalLiabilities                          0   0.00            0
totalCurrentLiabilities                   0   0.00            0
currentAccountsPayable                   57  16.76            0
deferredRevenue                         128  37.65            0
currentDebt                              32   9.41            0
shortTermDebt                             0   0.00            0
totalNonCurrentLiabilities                0   0.00            0
capitalLeaseObligations                 127  37.35            0
longTermDebt                              4   1.18            0
currentLongTermDebt                      12   3.53            0
longTermDebtNoncurrent                  107  31.47            0
shortLongTermDebtTotal                    0   0.00            0
otherCurrentLiabilities                   6   1.76            0
otherNonCurrentLiabilities               15   4.41            0
totalShareholderEquity                    0   0.00            0
treasuryStock                           105  30.88            0
retainedEarnings                          0   0.00            0
commonStock                               4   1.18            0
commonStockSharesOutstanding              0   0.00            0
symbol                                    0   0.00            0
sector                                    0   0.00            0
year                                      0   0.00            0

In [165]:
balance_df.fillna(0, inplace=True)

In [166]:
balance_df['totalLiabilities']

0      1.821080e+11
1      1.763320e+11
2      1.798130e+11
3      1.835460e+11
4      1.806880e+11
           ...
335    6.001400e+10
336    4.110800e+10
337    3.102600e+10
338    3.232200e+10
339    1.320700e+10
Name: totalLiabilities, Length: 340, dtype: float64

In [170]:
balance_df['totalLiabilities'].astype(int)

0     -2147483648
1     -2147483648
2     -2147483648
3     -2147483648
4     -2147483648
          ...
335   -2147483648
336   -2147483648
337   -2147483648
338   -2147483648
339   -2147483648
Name: totalLiabilities, Length: 340, dtype: int32

In [169]:
balance_df['totalLiabilities'].astype('int64')

0      182108000000
1      176332000000
2      179813000000
3      183546000000
4      180688000000
           ...
335     60014000000
336     41108000000
337     31026000000
338     32322000000
339     13207000000
Name: totalLiabilities, Length: 340, dtype: int64

In [171]:
bce_num = balance_df.select_dtypes(include=[np.number]).columns

In [172]:
for element in bce_num:
    balance_df[element] = balance_df[element].astype('int64')

In [173]:
open_data(balance_df)

Data shape is (340, 41).

fiscalDateEnding                          object
reportedCurrency                          object
totalAssets                                int64
totalCurrentAssets                         int64
cashAndCashEquivalentsAtCarryingValue      int64
cashAndShortTermInvestments                int64
inventory                                  int64
currentNetReceivables                      int64
totalNonCurrentAssets                      int64
propertyPlantEquipment                     int64
accumulatedDepreciationAmortizationPPE     int64
intangibleAssets                           int64
intangibleAssetsExcludingGoodwill          int64
goodwill                                   int64
investments                                int64
longTermInvestments                        int64
shortTermInvestments                       int64
otherCurrentAssets                         int64
otherNonCurrentAssets                      int64
totalLiabilities                           int64
totalCurrentLiabilities                    int64
currentAccountsPayable                     int64
deferredRevenue                            int64
currentDebt                                int64
shortTermDebt                              int64
totalNonCurrentLiabilities                 int64
capitalLeaseObligations                    int64
longTermDebt                               int64
currentLongTermDebt                        int64
longTermDebtNoncurrent                     int64
shortLongTermDebtTotal                     int64
otherCurrentLiabilities                    int64
otherNonCurrentLiabilities                 int64
totalShareholderEquity                     int64
treasuryStock                              int64
retainedEarnings                           int64
commonStock                                int64
commonStockSharesOutstanding               int64
symbol                                    object
sector                                    object
year                                       int64
dtype: object

Data row sample and full columns:

,fiscalDateEnding,reportedCurrency,totalAssets,totalCurrentAssets,cashAndCashEquivalentsAtCarryingValue,cashAndShortTermInvestments,inventory,currentNetReceivables,totalNonCurrentAssets,propertyPlantEquipment,accumulatedDepreciationAmortizationPPE,intangibleAssets,intangibleAssetsExcludingGoodwill,goodwill,investments,longTermInvestments,shortTermInvestments,otherCurrentAssets,otherNonCurrentAssets,totalLiabilities,totalCurrentLiabilities,currentAccountsPayable,deferredRevenue,currentDebt,shortTermDebt,totalNonCurrentLiabilities,capitalLeaseObligations,longTermDebt,currentLongTermDebt,longTermDebtNoncurrent,shortLongTermDebtTotal,otherCurrentLiabilities,otherNonCurrentLiabilities,totalShareholderEquity,treasuryStock,retainedEarnings,commonStock,commonStockSharesOutstanding,symbol,sector,year
323,2022-01-30,USD,44187000000,28829000000,1990000000,21208000000,2605000000,4650000000,15624000000,2778000000,1903000000,6688000000,2339000000,4349000000,40397000000,266000000,19218000000,366000000,3841000000,17575000000,4335000000,1783000000,1004000000,0,0,14667000000,741000000,10946000000,0,10946000000,10946000000,2108000000,1553000000,26612000000,0,16235000000,3000000,2506000000,NVDA,Tecnologia de la Informacion,2022
30,2018-12-31,USD,146130000000,2730000000,551000000,551000000,0,1733000000,143718000000,35126000000,23075000000,106755000000,77201000000,29554000000,476000000,0,0,446000000,1622000000,109845000000,12095000000,758000000,494000000,3290000000,3290000000,72469000000,0,72827000000,3290000000,69537000000,72827000000,7553000000,2837000000,36285000000,0,2780000000,36285000000,227005966,CHTR,Comunicacion,2018
86,2020-12-31,USD,52626800000,6243200000,3449100000,3449100000,51100000,2110300000,46383600000,24958200000,16518300000,2773100000,3464300000,2773100000,1297200000,1297200000,1297000000,632700000,3527400000,60451700000,6181200000,741300000,702000000,2243600000,3646600000,54270500000,13321300000,37440400000,2243600000,35196800000,37400000000,825200000,1054100000,-7824900000,67066400000,53908100000,16600000,745200000,MCD,Consumo Discrecional,2020
310,2021-09-30,USD,351002000000,134836000000,34940000000,62639000000,6580000000,51506000000,216166000000,39440000000,70283000000,0,0,0,318994000000,127877000000,27699000000,14111000000,48849000000,287912000000,125481000000,54763000000,19512000000,15692000000,6000000000,162431000000,769000000,118700000000,9613000000,109106000000,241783000000,47493000000,53325000000,63090000000,0,5562000000,57365000000,16426786000,AAPL,Tecnologia de la Informacion,2021
127,2022-12-31,USD,948465000000,334159000000,35811000000,308793000000,25366000000,0,150367000000,15584000000,0,101758000000,23639000000,78119000000,53178000000,28050000000,308793000000,26543000000,0,466784000000,62502000000,0,0,0,2429000000,76069000000,0,22805000000,2429000000,0,22805000000,8618000000,0,473424000000,67826000000,511127000000,8000000,3499349059,BRK-B,Finanzas,2022

In [174]:
balance_df

,fiscalDateEnding,reportedCurrency,totalAssets,totalCurrentAssets,cashAndCashEquivalentsAtCarryingValue,cashAndShortTermInvestments,inventory,currentNetReceivables,totalNonCurrentAssets,propertyPlantEquipment,accumulatedDepreciationAmortizationPPE,intangibleAssets,intangibleAssetsExcludingGoodwill,goodwill,investments,longTermInvestments,shortTermInvestments,otherCurrentAssets,otherNonCurrentAssets,totalLiabilities,totalCurrentLiabilities,currentAccountsPayable,deferredRevenue,currentDebt,shortTermDebt,totalNonCurrentLiabilities,capitalLeaseObligations,longTermDebt,currentLongTermDebt,longTermDebtNoncurrent,shortLongTermDebtTotal,otherCurrentLiabilities,otherNonCurrentLiabilities,totalShareholderEquity,treasuryStock,retainedEarnings,commonStock,commonStockSharesOutstanding,symbol,sector,year
0,2023-12-31,USD,264811000000,23987000000,6215000000,6525000000,0,13813000000,272139000000,59686000000,58701000000,183035000000,123767000000,59268000000,9694000000,9385000000,310000000,3959000000,12333000000,182108000000,40198000000,12437000000,3860000000,2069000000,2069000000,147602000000,0,103200000000,2069000000,92200000000,103200000000,22450000000,20122000000,82703000000,7517000000,52892000000,48000000,4008000000,CMCSA,Comunicacion,2023
1,2022-12-31,USD,257275000000,21826000000,4749000000,5151000000,0,12672000000,276545000000,55485000000,56900000000,193402000000,134908000000,58494000000,8142000000,7740000000,402000000,4406000000,12497000000,176332000000,27887000000,12544000000,3115000000,1743000000,1743000000,149019000000,0,100900000000,1743000000,86900000000,100900000000,11220000000,20395000000,80943000000,7517000000,51609000000,51000000,4277000000,CMCSA,Comunicacion,2022
2,2021-12-31,USD,275905000000,24807000000,8711000000,9079000000,0,12008000000,298168000000,54000000000,55600000000,215504000000,145315000000,70200000000,9055000000,8082000000,368000000,4088000000,12424000000,179813000000,29348000000,12455000000,3735000000,2132000000,2132000000,150547000000,0,111432000000,2132000000,109300000000,100802000000,11721000000,20620000000,96092000000,7517000000,61902000000,54000000,4557000000,CMCSA,Comunicacion,2021
3,2020-12-31,USD,273869000000,26741000000,11740000000,12032000000,0,11466000000,290953000000,51995000000,54388000000,218146000000,147477000000,70700000000,8559000000,7820000000,292000000,3535000000,8103000000,183546000000,28796000000,11364000000,3713000000,3146000000,3146000000,151377000000,0,128746000000,3146000000,125600000000,105409000000,11323000000,18222000000,90323000000,7517000000,56438000000,54000000,4583000000,CMCSA,Comunicacion,2020
4,2019-12-31,USD,263414000000,25392000000,5500000000,7209000000,3877000000,11292000000,281532000000,48322000000,53239000000,215971000000,147246000000,68725000000,9392000000,6989000000,1709000000,4723000000,8866000000,180688000000,30292000000,10826000000,3386000000,4452000000,4452000000,144328000000,0,103890000000,4452000000,115800000000,103890000000,12246000000,16765000000,82726000000,7517000000,50695000000,54000000,4560000000,CMCSA,Comunicacion,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335,2022-12-31,USD,185727000000,59549000000,14681000000,40763000000,0,13466000000,40476000000,79518000000,0,21203000000,897000000,20306000000,52106000000,17000000,26082000000,5345000000,6583000000,60014000000,27026000000,6107000000,1008000000,129000000,10000000000,40191000000,558000000,9923000000,0,9923000000,19923000000,4906000000,7764000000,125713000000,0,64799000000,0,2639000000,META,Tecnologia de la Informacion,2022
336,2021-12-31,USD,165987000000,66666000000,16601000000,47998000000,0,14039000000,34771000000,57809000000,0,19831000000,634000000,19197000000,62828000000,34000000,31397000000,4629000000,2751000000,41108000000,21135000000,5135000000,1113000000,75000000,1127000000,26417000000,506000000,0,0,0,13873000000,15364000000,7227000000,124879000000,0,69761000000,0,2764000000,META,Tecnologia de la Informacion,2021
337,2020-12-31,USD,159316000000,75670000000,17576000000,61954000000,0,11335000000,31779000000,45633000000,0,19673000000,623000000,19050000000,88756000000,62000000,44378000000,2381000000,2758000000,31026000000,14981000000,1331000000,717000000,54000000,1023000000,21539000000,469000000,0,0,0,10654000000,12245000000,6414000000,128290000000,0,77345000000,0,2854000000,META,Tecnologia de la Informacion,2020
338,2019-12-31,USD,133376000000,66225000000,19079000000,54855000000,0,9518000000,31828000000,35323000000,10663000000,19609000000,894000000,18715000000,71552000000,0,35776000000,1852000000,2673000000,32322000000,15053000000,1363000000,503000000,855000000,800000000,18308000000,418000000,0,800000000,0,10324000000,12621000000,7745000000,101054000000,0,55692000000,0,2851000000,META,Tecnologia de la Informacion,2019
339,2018-12-31,USD,97334000000,50480000000,10019000000,41114000000,0,7587000000,46854000000,24683000000,6890000000,19595000000,1294000000,18301000000,62190000000,0,31095000000,1779000000,2576000000,13207000000,7017000000,820000000,264000000,0,500000000,6190000000,418000000,0,500000000,0,500000000,5550000000,6190000000,84127000000,0,41981000000,0,2875000000,META,Tecnologia de la Informacion,2018

In [175]:
balance_df.nunique()

fiscalDateEnding                           49
reportedCurrency                            1
totalAssets                               340
totalCurrentAssets                        340
cashAndCashEquivalentsAtCarryingValue     337
cashAndShortTermInvestments               339
inventory                                 306
currentNetReceivables                     291
totalNonCurrentAssets                     340
propertyPlantEquipment                    337
accumulatedDepreciationAmortizationPPE    249
intangibleAssets                          301
intangibleAssetsExcludingGoodwill         290
goodwill                                  263
investments                               290
longTermInvestments                       263
shortTermInvestments                      263
otherCurrentAssets                        335
otherNonCurrentAssets                     277
totalLiabilities                          340
totalCurrentLiabilities                   339
currentAccountsPayable                    283
deferredRevenue                           209
currentDebt                               300
shortTermDebt                             309
totalNonCurrentLiabilities                340
capitalLeaseObligations                   206
longTermDebt                              334
currentLongTermDebt                       301
longTermDebtNoncurrent                    233
shortLongTermDebtTotal                    339
otherCurrentLiabilities                   332
otherNonCurrentLiabilities                325
totalShareholderEquity                    340
treasuryStock                             202
retainedEarnings                          340
commonStock                               179
commonStockSharesOutstanding              328
symbol                                     55
sector                                     11
year                                        7
dtype: int64

In [177]:
balance_df.drop(columns=['reportedCurrency'], inplace=True)

In [179]:
balance_df

,fiscalDateEnding,totalAssets,totalCurrentAssets,cashAndCashEquivalentsAtCarryingValue,cashAndShortTermInvestments,inventory,currentNetReceivables,totalNonCurrentAssets,propertyPlantEquipment,accumulatedDepreciationAmortizationPPE,intangibleAssets,intangibleAssetsExcludingGoodwill,goodwill,investments,longTermInvestments,shortTermInvestments,otherCurrentAssets,otherNonCurrentAssets,totalLiabilities,totalCurrentLiabilities,currentAccountsPayable,deferredRevenue,currentDebt,shortTermDebt,totalNonCurrentLiabilities,capitalLeaseObligations,longTermDebt,currentLongTermDebt,longTermDebtNoncurrent,shortLongTermDebtTotal,otherCurrentLiabilities,otherNonCurrentLiabilities,totalShareholderEquity,treasuryStock,retainedEarnings,commonStock,commonStockSharesOutstanding,symbol,sector,year
0,2023-12-31,264811000000,23987000000,6215000000,6525000000,0,13813000000,272139000000,59686000000,58701000000,183035000000,123767000000,59268000000,9694000000,9385000000,310000000,3959000000,12333000000,182108000000,40198000000,12437000000,3860000000,2069000000,2069000000,147602000000,0,103200000000,2069000000,92200000000,103200000000,22450000000,20122000000,82703000000,7517000000,52892000000,48000000,4008000000,CMCSA,Comunicacion,2023
1,2022-12-31,257275000000,21826000000,4749000000,5151000000,0,12672000000,276545000000,55485000000,56900000000,193402000000,134908000000,58494000000,8142000000,7740000000,402000000,4406000000,12497000000,176332000000,27887000000,12544000000,3115000000,1743000000,1743000000,149019000000,0,100900000000,1743000000,86900000000,100900000000,11220000000,20395000000,80943000000,7517000000,51609000000,51000000,4277000000,CMCSA,Comunicacion,2022
2,2021-12-31,275905000000,24807000000,8711000000,9079000000,0,12008000000,298168000000,54000000000,55600000000,215504000000,145315000000,70200000000,9055000000,8082000000,368000000,4088000000,12424000000,179813000000,29348000000,12455000000,3735000000,2132000000,2132000000,150547000000,0,111432000000,2132000000,109300000000,100802000000,11721000000,20620000000,96092000000,7517000000,61902000000,54000000,4557000000,CMCSA,Comunicacion,2021
3,2020-12-31,273869000000,26741000000,11740000000,12032000000,0,11466000000,290953000000,51995000000,54388000000,218146000000,147477000000,70700000000,8559000000,7820000000,292000000,3535000000,8103000000,183546000000,28796000000,11364000000,3713000000,3146000000,3146000000,151377000000,0,128746000000,3146000000,125600000000,105409000000,11323000000,18222000000,90323000000,7517000000,56438000000,54000000,4583000000,CMCSA,Comunicacion,2020
4,2019-12-31,263414000000,25392000000,5500000000,7209000000,3877000000,11292000000,281532000000,48322000000,53239000000,215971000000,147246000000,68725000000,9392000000,6989000000,1709000000,4723000000,8866000000,180688000000,30292000000,10826000000,3386000000,4452000000,4452000000,144328000000,0,103890000000,4452000000,115800000000,103890000000,12246000000,16765000000,82726000000,7517000000,50695000000,54000000,4560000000,CMCSA,Comunicacion,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335,2022-12-31,185727000000,59549000000,14681000000,40763000000,0,13466000000,40476000000,79518000000,0,21203000000,897000000,20306000000,52106000000,17000000,26082000000,5345000000,6583000000,60014000000,27026000000,6107000000,1008000000,129000000,10000000000,40191000000,558000000,9923000000,0,9923000000,19923000000,4906000000,7764000000,125713000000,0,64799000000,0,2639000000,META,Tecnologia de la Informacion,2022
336,2021-12-31,165987000000,66666000000,16601000000,47998000000,0,14039000000,34771000000,57809000000,0,19831000000,634000000,19197000000,62828000000,34000000,31397000000,4629000000,2751000000,41108000000,21135000000,5135000000,1113000000,75000000,1127000000,26417000000,506000000,0,0,0,13873000000,15364000000,7227000000,124879000000,0,69761000000,0,2764000000,META,Tecnologia de la Informacion,2021
337,2020-12-31,159316000000,75670000000,17576000000,61954000000,0,11335000000,31779000000,45633000000,0,19673000000,623000000,19050000000,88756000000,62000000,44378000000,2381000000,2758000000,31026000000,14981000000,1331000000,717000000,54000000,1023000000,21539000000,469000000,0,0,0,10654000000,12245000000,6414000000,128290000000,0,77345000000,0,2854000000,META,Tecnologia de la Informacion,2020
338,2019-12-31,133376000000,66225000000,19079000000,54855000000,0,9518000000,31828000000,35323000000,10663000000,19609000000,894000000,18715000000,71552000000,0,35776000000,1852000000,2673000000,32322000000,15053000000,1363000000,503000000,855000000,800000000,18308000000,418000000,0,800000000,0,10324000000,12621000000,7745000000,101054000000,0,55692000000,0,2851000000,META,Tecnologia de la Informacion,2019
339,2018-12-31,97334000000,50480000000,10019000000,41114000000,0,7587000000,46854000000,24683000000,6890000000,19595000000,1294000000,18301000000,62190000000,0,31095000000,1779000000,2576000000,13207000000,7017000000,820000000,264000000,0,500000000,6190000000,418000000,0,500000000,0,500000000,5550000000,6190000000,84127000000,0,41981000000,0,2875000000,META,Tecnologia de la Informacion,2018

In [224]:
balance_df.reset_index(drop=False,inplace=True)
balance_df.rename(columns={"index": "balance_id"}, inplace=True)
balance_df.columns = balance_df.columns.str.replace('(?<=[a-z])(?=[A-Z])', '_', regex=True).str.lower()
balance_df['company_id'] = balance_df['symbol'].map(symbol_to_id_map)
balance_df['name'] = balance_df['symbol'].map(symbol_to_name_map)
balance_df

,balance_id,fiscal_date_ending,total_assets,total_current_assets,cash_and_cash_equivalents_at_carrying_value,cash_and_short_term_investments,inventory,current_net_receivables,total_non_current_assets,property_plant_equipment,accumulated_depreciation_amortization_ppe,intangible_assets,intangible_assets_excluding_goodwill,goodwill,investments,long_term_investments,short_term_investments,other_current_assets,other_non_current_assets,total_liabilities,total_current_liabilities,current_accounts_payable,deferred_revenue,current_debt,short_term_debt,total_non_current_liabilities,capital_lease_obligations,long_term_debt,current_long_term_debt,long_term_debt_noncurrent,short_long_term_debt_total,other_current_liabilities,other_non_current_liabilities,total_shareholder_equity,treasury_stock,retained_earnings,common_stock,common_stock_shares_outstanding,symbol,sector,year,company_id,name
0,0,2023-12-31,264811000000,23987000000,6215000000,6525000000,0,13813000000,272139000000,59686000000,58701000000,183035000000,123767000000,59268000000,9694000000,9385000000,310000000,3959000000,12333000000,182108000000,40198000000,12437000000,3860000000,2069000000,2069000000,147602000000,0,103200000000,2069000000,92200000000,103200000000,22450000000,20122000000,82703000000,7517000000,52892000000,48000000,4008000000,CMCSA,Comunicacion,2023,0,Comcast Corp
1,1,2022-12-31,257275000000,21826000000,4749000000,5151000000,0,12672000000,276545000000,55485000000,56900000000,193402000000,134908000000,58494000000,8142000000,7740000000,402000000,4406000000,12497000000,176332000000,27887000000,12544000000,3115000000,1743000000,1743000000,149019000000,0,100900000000,1743000000,86900000000,100900000000,11220000000,20395000000,80943000000,7517000000,51609000000,51000000,4277000000,CMCSA,Comunicacion,2022,0,Comcast Corp
2,2,2021-12-31,275905000000,24807000000,8711000000,9079000000,0,12008000000,298168000000,54000000000,55600000000,215504000000,145315000000,70200000000,9055000000,8082000000,368000000,4088000000,12424000000,179813000000,29348000000,12455000000,3735000000,2132000000,2132000000,150547000000,0,111432000000,2132000000,109300000000,100802000000,11721000000,20620000000,96092000000,7517000000,61902000000,54000000,4557000000,CMCSA,Comunicacion,2021,0,Comcast Corp
3,3,2020-12-31,273869000000,26741000000,11740000000,12032000000,0,11466000000,290953000000,51995000000,54388000000,218146000000,147477000000,70700000000,8559000000,7820000000,292000000,3535000000,8103000000,183546000000,28796000000,11364000000,3713000000,3146000000,3146000000,151377000000,0,128746000000,3146000000,125600000000,105409000000,11323000000,18222000000,90323000000,7517000000,56438000000,54000000,4583000000,CMCSA,Comunicacion,2020,0,Comcast Corp
4,4,2019-12-31,263414000000,25392000000,5500000000,7209000000,3877000000,11292000000,281532000000,48322000000,53239000000,215971000000,147246000000,68725000000,9392000000,6989000000,1709000000,4723000000,8866000000,180688000000,30292000000,10826000000,3386000000,4452000000,4452000000,144328000000,0,103890000000,4452000000,115800000000,103890000000,12246000000,16765000000,82726000000,7517000000,50695000000,54000000,4560000000,CMCSA,Comunicacion,2019,0,Comcast Corp
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335,335,2022-12-31,185727000000,59549000000,14681000000,40763000000,0,13466000000,40476000000,79518000000,0,21203000000,897000000,20306000000,52106000000,17000000,26082000000,5345000000,6583000000,60014000000,27026000000,6107000000,1008000000,129000000,10000000000,40191000000,558000000,9923000000,0,9923000000,19923000000,4906000000,7764000000,125713000000,0,64799000000,0,2639000000,META,Tecnologia de la Informacion,2022,54,Meta Platforms Inc.
336,336,2021-12-31,165987000000,66666000000,16601000000,47998000000,0,14039000000,34771000000,57809000000,0,19831000000,634000000,19197000000,62828000000,34000000,31397000000,4629000000,2751000000,41108000000,21135000000,5135000000,1113000000,75000000,1127000000,26417000000,506000000,0,0,0,13873000000,15364000000,7227000000,124879000000,0,69761000000,0,2764000000,META,Tecnologia de la Informacion,2021,54,Meta Platforms Inc.
337,337,2020-12-31,159316000000,75670000000,17576000000,61954000000,0,11335000000,31779000000,45633000000,0,19673000000,623000000,19050000000,88756000000,62000000,44378000000,2381000000,2758000000,31026000000,14981000000,1331000000,717000000,54000000,1023000000,21539000000,469000000,0,0,0,10654000000,12245000000,6414000000,128290000000,0,77345000000,0,2854000000,META,Tecnologia de la Informacion,2020,54,Meta Platforms Inc.
338,338,2019-12-31,133376000000,66225000000,19079000000,54855000000,0,9518000000,31828000000,35323000000,10663000000,19609000000,894000000,18715000000,71552000000,0,35776000000,1852000000,2673000000,32322000000,15053000000,1363000000,503000000,855000000,800000000,18308000000,418000000,0,800000000,0,10324000000,12621000000,7745000000,101054000000,0,55692000000,0,2851000000,META,Tecnologia de la Informacion,2019,54,Meta Platforms Inc.
339,339,2018-12-31,97334000000,50480000000,10019000000,41114000000,0,7587000000,46854000000,24683000000,6890000000,19595000000,1294000000,18301000000,62190000000,0,31095000000,1779000000,2576000000,13207000000,7017000000,820000000,264000000,0,500000000,6190000000,418000000,0,500000000,0,500000000,5550000000,6190000000,84127000000,0,41981000000,0,2875000000,META,Tecnologia de la Informacion,2018,54,Meta Platforms Inc.

In [225]:
balance_df.to_csv('2_balance.csv', index=False)

In [186]:
explore_data(cf_df)

There are 0 duplicate rows. Also;

,NaN,NaN %,EmptySpaces
fiscalDateEnding,0,0.0,0
reportedCurrency,0,0.0,0
operatingCashflow,0,0.0,0
paymentsForOperatingActivities,0,0.0,0
proceedsFromOperatingActivities,0,0.0,0
changeInOperatingLiabilities,0,0.0,0
changeInOperatingAssets,0,0.0,0
depreciationDepletionAndAmortization,0,0.0,0
capitalExpenditures,0,0.0,0
changeInReceivables,0,0.0,0
changeInInventory,0,0.0,0
profitLoss,0,0.0,0
cashflowFromInvestment,0,0.0,0
cashflowFromFinancing,0,0.0,0
proceedsFromRepaymentsOfShortTermDebt,0,0.0,0
paymentsForRepurchaseOfCommonStock,0,0.0,0
paymentsForRepurchaseOfEquity,0,0.0,0
paymentsForRepurchaseOfPreferredStock,0,0.0,0
dividendPayout,0,0.0,0
dividendPayoutCommonStock,0,0.0,0
dividendPayoutPreferredStock,0,0.0,0
proceedsFromIssuanceOfCommonStock,0,0.0,0
proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet,0,0.0,0
proceedsFromIssuanceOfPreferredStock,0,0.0,0
proceedsFromRepurchaseOfEquity,0,0.0,0
proceedsFromSaleOfTreasuryStock,0,0.0,0
changeInCashAndCashEquivalents,0,0.0,0
changeInExchangeRate,0,0.0,0
netIncome,0,0.0,0
symbol,0,0.0,0
sector,0,0.0,0
year,0,0.0,0

In [185]:
cf_df.fillna(0, inplace=True)

In [189]:
cf_df.drop(columns=['reportedCurrency'], inplace=True)

In [190]:
cf_df.head(1)

,fiscalDateEnding,operatingCashflow,paymentsForOperatingActivities,proceedsFromOperatingActivities,changeInOperatingLiabilities,changeInOperatingAssets,depreciationDepletionAndAmortization,capitalExpenditures,changeInReceivables,changeInInventory,profitLoss,cashflowFromInvestment,cashflowFromFinancing,proceedsFromRepaymentsOfShortTermDebt,paymentsForRepurchaseOfCommonStock,paymentsForRepurchaseOfEquity,paymentsForRepurchaseOfPreferredStock,dividendPayout,dividendPayoutCommonStock,dividendPayoutPreferredStock,proceedsFromIssuanceOfCommonStock,proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet,proceedsFromIssuanceOfPreferredStock,proceedsFromRepurchaseOfEquity,proceedsFromSaleOfTreasuryStock,changeInCashAndCashEquivalents,changeInExchangeRate,netIncome,symbol,sector,year
0,2023-12-31,28501000000,4.674000e+09,0.0,-520000000.0,0.0,14336000000,1.554000e+10,0.0,1.516000e+09,15107000000,-7161000000,-19850000000,-660000000.0,1.129100e+10,1.129100e+10,0.0,4.766000e+09,4.766000e+09,0.0,0.0,6.052000e+09,0.0,-1.129100e+10,0.0,0.0,0.0,15388000000,CMCSA,Comunicacion,2023

In [194]:
cf_num = cf_df.select_dtypes(include=[np.number]).columns
cf_num

Index(['operatingCashflow', 'paymentsForOperatingActivities',
       'proceedsFromOperatingActivities', 'changeInOperatingLiabilities',
       'changeInOperatingAssets', 'depreciationDepletionAndAmortization',
       'capitalExpenditures', 'changeInReceivables', 'changeInInventory',
       'profitLoss', 'cashflowFromInvestment', 'cashflowFromFinancing',
       'proceedsFromRepaymentsOfShortTermDebt',
       'paymentsForRepurchaseOfCommonStock', 'paymentsForRepurchaseOfEquity',
       'paymentsForRepurchaseOfPreferredStock', 'dividendPayout',
       'dividendPayoutCommonStock', 'dividendPayoutPreferredStock',
       'proceedsFromIssuanceOfCommonStock',
       'proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet',
       'proceedsFromIssuanceOfPreferredStock',
       'proceedsFromRepurchaseOfEquity', 'proceedsFromSaleOfTreasuryStock',
       'changeInCashAndCashEquivalents', 'changeInExchangeRate', 'netIncome',
       'year'],
      dtype='object')

In [197]:
for element in cf_num:
    cf_df[element] = cf_df[element].astype('int64')

In [198]:
open_data(cf_df)

Data shape is (329, 31).

fiscalDateEnding                                             datetime64[ns]
operatingCashflow                                                     int64
paymentsForOperatingActivities                                        int64
proceedsFromOperatingActivities                                       int64
changeInOperatingLiabilities                                          int64
changeInOperatingAssets                                               int64
depreciationDepletionAndAmortization                                  int64
capitalExpenditures                                                   int64
changeInReceivables                                                   int64
changeInInventory                                                     int64
profitLoss                                                            int64
cashflowFromInvestment                                                int64
cashflowFromFinancing                                                 int64
proceedsFromRepaymentsOfShortTermDebt                                 int64
paymentsForRepurchaseOfCommonStock                                    int64
paymentsForRepurchaseOfEquity                                         int64
paymentsForRepurchaseOfPreferredStock                                 int64
dividendPayout                                                        int64
dividendPayoutCommonStock                                             int64
dividendPayoutPreferredStock                                          int64
proceedsFromIssuanceOfCommonStock                                     int64
proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet             int64
proceedsFromIssuanceOfPreferredStock                                  int64
proceedsFromRepurchaseOfEquity                                        int64
proceedsFromSaleOfTreasuryStock                                       int64
changeInCashAndCashEquivalents                                        int64
changeInExchangeRate                                                  int64
netIncome                                                             int64
symbol                                                               object
sector                                                               object
year                                                                  int64
dtype: object

Data row sample and full columns:

,fiscalDateEnding,operatingCashflow,paymentsForOperatingActivities,proceedsFromOperatingActivities,changeInOperatingLiabilities,changeInOperatingAssets,depreciationDepletionAndAmortization,capitalExpenditures,changeInReceivables,changeInInventory,profitLoss,cashflowFromInvestment,cashflowFromFinancing,proceedsFromRepaymentsOfShortTermDebt,paymentsForRepurchaseOfCommonStock,paymentsForRepurchaseOfEquity,paymentsForRepurchaseOfPreferredStock,dividendPayout,dividendPayoutCommonStock,dividendPayoutPreferredStock,proceedsFromIssuanceOfCommonStock,proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet,proceedsFromIssuanceOfPreferredStock,proceedsFromRepurchaseOfEquity,proceedsFromSaleOfTreasuryStock,changeInCashAndCashEquivalents,changeInExchangeRate,netIncome,symbol,sector,year
285,2019-12-31,5781000000,3448000000,0,-641000000,-580000000,89000000,7814000000,-630000000,120000000,4744000000,-3392000000,-1930000000,-1500000000,0,0,0,2570000000,2570000000,0,844000000,5220000000,0,1688000000,0,459000000,0,4739000000,SO,Servicios Publicos,2019
322,2018-12-31,47971000000,69000000,0,10052000000,3376000000,9035000000,25139000000,2169000000,7890000000,30736000000,-28504000000,-13179000000,0,9075000000,9075000000,0,0,0,0,0,0,0,-9075000000,0,5986000000,-302000000,30736000000,GOOGL,Tecnologia de la Informacion,2018
168,2022-12-31,5916000000,4254000000,0,1308000000,5352000000,1742000000,1174000000,2719000000,1925000000,407000000,2270000000,-5585000000,65000000,1048000000,1048000000,144000000,639000000,639000000,0,0,0,0,-1048000000,0,2601000000,0,339000000,GE,Industriales,2022
212,2020-12-31,7429000000,2017000000,0,109000000,-165000000,4626000000,3400000000,-19000000,-18000000,2626000000,-2986000000,-3345000000,1198000000,2457000000,2457000000,0,2028000000,2028000000,0,47000000,2796000000,0,-2410000000,0,7984000000,0,2501000000,LIN,Materiales,2020
95,2023-12-31,35609000000,14287000000,0,-2850000000,485000000,17326000000,15829000000,-1337000000,320000000,21411000000,-15232000000,-30109000000,135000000,14939000000,14939000000,0,11376000000,11336000000,0,0,150000000,0,-14678000000,0,0,0,21369000000,CVX,Energia,2023

In [ ]:
cf_df.reset_index(drop=False,inplace=True)
cf_df.rename(columns={"index": "cf_id"}, inplace=True)
cf_df.columns = cf_df.columns.str.replace('(?<=[a-z])(?=[A-Z])', '_', regex=True).str.lower()
cf_df['company_id'] = cf_df['symbol'].map(symbol_to_id_map)
cf_df['name'] = cf_df['symbol'].map(symbol_to_name_map)
cf_df

,cf_id,fiscal_date_ending,operating_cashflow,payments_for_operating_activities,proceeds_from_operating_activities,change_in_operating_liabilities,change_in_operating_assets,depreciation_depletion_and_amortization,capital_expenditures,change_in_receivables,change_in_inventory,profit_loss,cashflow_from_investment,cashflow_from_financing,proceeds_from_repayments_of_short_term_debt,payments_for_repurchase_of_common_stock,payments_for_repurchase_of_equity,payments_for_repurchase_of_preferred_stock,dividend_payout,dividend_payout_common_stock,dividend_payout_preferred_stock,proceeds_from_issuance_of_common_stock,proceeds_from_issuance_of_long_term_debt_and_capital_securities_net,proceeds_from_issuance_of_preferred_stock,proceeds_from_repurchase_of_equity,proceeds_from_sale_of_treasury_stock,change_in_cash_and_cash_equivalents,change_in_exchange_rate,net_income,symbol,sector,year,company_id
0,0,2023-12-31,28501000000,4674000000,0,-520000000,0,14336000000,15540000000,0,1516000000,15107000000,-7161000000,-19850000000,-660000000,11291000000,11291000000,0,4766000000,4766000000,0,0,6052000000,0,-11291000000,0,0,0,15388000000,CMCSA,Comunicacion,2023,0
1,1,2022-12-31,26413000000,4378000000,0,497000000,0,13821000000,13767000000,0,830000000,4925000000,-14140000000,-16184000000,660000000,13328000000,13328000000,0,4741000000,4741000000,0,0,2745000000,0,-13328000000,0,-3911000000,0,5370000000,CMCSA,Comunicacion,2022,0
2,2,2021-12-31,29146000000,4895000000,0,765000000,0,13804000000,12057000000,0,570000000,13833000000,-13446000000,-18618000000,0,4672000000,4672000000,0,4532000000,4532000000,0,0,2628000000,0,-4672000000,0,-2918000000,0,14159000000,CMCSA,Comunicacion,2021,0
3,3,2020-12-31,24737000000,4814000000,0,-266000000,0,13100000000,11634000000,0,286000000,10701000000,-12047000000,-6513000000,0,534000000,534000000,0,4140000000,4140000000,0,0,18644000000,0,-534000000,0,6177000000,0,10534000000,CMCSA,Comunicacion,2020,0
4,4,2019-12-31,25697000000,5168000000,0,-347000000,0,12953000000,12428000000,0,404000000,13323000000,-14841000000,-9181000000,-1288000000,504000000,504000000,0,3735000000,3735000000,0,0,5479000000,0,-504000000,0,1675000000,0,13057000000,CMCSA,Comunicacion,2019,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
324,324,2022-12-31,50475000000,1670000000,0,5396000000,-287000000,8686000000,31431000000,-231000000,0,23200000000,-28970000000,-22136000000,0,27956000000,27956000000,0,0,0,0,0,9921000000,0,-27956000000,0,-631000000,0,23200000000,META,Tecnologia de la Informacion,2022,54
325,325,2021-12-31,57683000000,1421000000,0,5909000000,5209000000,7967000000,18567000000,3110000000,2187000000,39370000000,-7570000000,-50728000000,14000000,44537000000,44537000000,0,0,0,0,0,0,0,-44537000000,0,-615000000,0,39370000000,META,Tecnologia de la Informacion,2021,54
326,326,2020-12-31,38747000000,1222000000,0,-1312000000,1411000000,6862000000,15115000000,1512000000,-1302000000,29146000000,-30059000000,-10292000000,24000000,6272000000,6272000000,0,0,0,0,0,0,0,-6272000000,0,-1604000000,0,29146000000,META,Tecnologia de la Informacion,2020,54
327,327,2019-12-31,36314000000,914000000,0,9123000000,1873000000,5741000000,15102000000,1961000000,8975000000,18485000000,-19864000000,-7299000000,-223000000,4202000000,4202000000,0,2337000000,2337000000,0,0,0,0,-4202000000,0,9151000000,0,18485000000,META,Tecnologia de la Informacion,2019,54
328,328,2018-12-31,29274000000,1000000,0,1057000000,2741000000,4315000000,13915000000,1892000000,91000000,22112000000,-11603000000,-15572000000,500000000,12879000000,12879000000,0,0,0,0,0,0,0,-12879000000,0,2099000000,0,22112000000,META,Tecnologia de la Informacion,2018,54

In [227]:
cf_df.to_csv('3_cash_flow.csv', index=False)

In [203]:
explore_data(income_df)

There are 0 duplicate rows. Also;

                                   NaN  NaN %  EmptySpaces
fiscalDateEnding                     0   0.00            0
reportedCurrency                     0   0.00            0
grossProfit                          0   0.00            0
totalRevenue                         0   0.00            0
costOfRevenue                        0   0.00            0
costofGoodsAndServicesSold           3   0.91            0
operatingIncome                      0   0.00            0
sellingGeneralAndAdministrative      0   0.00            0
researchAndDevelopment             143  43.47            0
operatingExpenses                    0   0.00            0
investmentIncomeNet                166  50.46            0
netInterestIncome                    0   0.00            0
interestIncome                      26   7.90            0
interestExpense                      0   0.00            0
nonInterestIncome                   26   7.90            0
otherNonOperatingIncome             66  20.06            0
depreciation                       140  42.55            0
depreciationAndAmortization          0   0.00            0
incomeBeforeTax                      0   0.00            0
incomeTaxExpense                     0   0.00            0
interestAndDebtExpense              19   5.78            0
netIncomeFromContinuingOperations    0   0.00            0
comprehensiveIncomeNetOfTax          0   0.00            0
ebit                                 0   0.00            0
ebitda                               0   0.00            0
netIncome                            0   0.00            0
symbol                               0   0.00            0
sector                               0   0.00            0
year                                 0   0.00            0

In [ ]:
income_df.fillna(0, inplace=True)
income_df.drop(columns=['reportedCurrency'], inplace=True)
inc_num = income_df.select_dtypes(include=[np.number]).columns
for element in inc_num:
    income_df[element] = income_df[element].astype('int64')
income_df.reset_index(drop=False,inplace=True)
income_df.rename(columns={"index": "income_id"}, inplace=True)
income_df.columns = income_df.columns.str.replace('(?<=[a-z])(?=[A-Z])', '_', regex=True).str.lower()
income_df['company_id'] = income_df['symbol'].map(symbol_to_id_map)
income_df['name'] = income_df['symbol'].map(symbol_to_name_map)
income_df

,income_id,fiscal_date_ending,gross_profit,total_revenue,cost_of_revenue,costof_goods_and_services_sold,operating_income,selling_general_and_administrative,research_and_development,operating_expenses,investment_income_net,net_interest_income,interest_income,interest_expense,non_interest_income,other_non_operating_income,depreciation,depreciation_and_amortization,income_before_tax,income_tax_expense,interest_and_debt_expense,net_income_from_continuing_operations,comprehensive_income_net_of_tax,ebit,ebitda,net_income,symbol,sector,year,company_id
0,0,2023-12-31,107098000000,121572000000,14474000000,36762000000,23314000000,8992000000,0,15249000000,0,-4087000000,0,4087000000,0,592000000,8854000000,5482000000,20759000000,5371000000,4087000000,15107000000,16746000000,24846000000,30328000000,15388000000,CMCSA,Comunicacion,2023,0
1,1,2022-12-31,98141000000,121427000000,23286000000,38213000000,14041000000,9606000000,0,24044000000,0,-3896000000,0,3896000000,0,-3000000,8724000000,5097000000,9729000000,4359000000,3896000000,4925000000,1280000000,13625000000,18722000000,5370000000,CMCSA,Comunicacion,2022,0
2,2,2021-12-31,93805000000,116385000000,22580000000,38450000000,20817000000,8776000000,0,22580000000,0,-4281000000,0,4281000000,0,2557000000,8628000000,13804000000,19418000000,5259000000,4281000000,13834000000,13755000000,23699000000,37503000000,14159000000,CMCSA,Comunicacion,2021,0
3,3,2020-12-31,82763000000,103564000000,20801000000,33121000000,17493000000,7701000000,0,20978000000,0,-4588000000,0,4588000000,0,1160000000,8320000000,13100000000,13898000000,3364000000,4588000000,10701000000,11371000000,18486000000,31586000000,10534000000,CMCSA,Comunicacion,2020,0
4,4,2019-12-31,87188000000,108942000000,21754000000,34440000000,21125000000,8442000000,0,21754000000,0,-4567000000,4416000000,4567000000,0,438000000,8663000000,12953000000,16730000000,3673000000,4567000000,13323000000,14472000000,21297000000,34250000000,13057000000,CMCSA,Comunicacion,2019,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
324,324,2022-12-31,91103000000,116352000000,25249000000,25249000000,28944000000,27078000000,35338000000,62981000000,461000000,-176000000,9000000,185000000,116528000000,-320000000,8500000000,565000000,28819000000,5619000000,176000000,23200000000,20363000000,28944000000,29560000000,23200000000,META,Tecnologia de la Informacion,2022,54
325,325,2021-12-31,95125000000,117774000000,22649000000,22649000000,46753000000,23872000000,24655000000,49278000000,0,-15000000,484000000,15000000,117789000000,210000000,7560000000,751000000,47284000000,7914000000,15000000,39370000000,37750000000,46753000000,48050000000,39370000000,META,Tecnologia de la Informacion,2021,54
326,326,2020-12-31,69130000000,85822000000,16692000000,16692000000,32671000000,18155000000,18447000000,37334000000,0,-14000000,672000000,14000000,85836000000,-34000000,6390000000,732000000,33180000000,4034000000,14000000,29146000000,30562000000,32671000000,33926000000,29146000000,META,Tecnologia de la Informacion,2020,54
327,327,2019-12-31,57802000000,70572000000,12770000000,12770000000,23986000000,20341000000,13600000000,34698000000,924000000,-20000000,924000000,20000000,70592000000,27000000,5180000000,757000000,24812000000,6327000000,20000000,18485000000,18756000000,24832000000,25589000000,18485000000,META,Tecnologia de la Informacion,2019,54
328,328,2018-12-31,46261000000,55616000000,9355000000,9355000000,24913000000,11297000000,10273000000,22287000000,661000000,-9000000,661000000,9000000,55625000000,9000000,3680000000,640000000,25361000000,3249000000,9000000,22112000000,21610000000,25370000000,26010000000,22112000000,META,Tecnologia de la Informacion,2018,54

In [206]:
open_data(income_df)

Data shape is (329, 30).

income_id                                         int64
fiscal_date_ending                       datetime64[ns]
gross_profit                                      int64
total_revenue                                     int64
cost_of_revenue                                   int64
costof_goods_and_services_sold                    int64
operating_income                                  int64
selling_general_and_administrative                int64
research_and_development                          int64
operating_expenses                                int64
investment_income_net                             int64
net_interest_income                               int64
interest_income                                   int64
interest_expense                                  int64
non_interest_income                               int64
other_non_operating_income                        int64
depreciation                                      int64
depreciation_and_amortization                     int64
income_before_tax                                 int64
income_tax_expense                                int64
interest_and_debt_expense                         int64
net_income_from_continuing_operations             int64
comprehensive_income_net_of_tax                   int64
ebit                                              int64
ebitda                                            int64
net_income                                        int64
symbol                                           object
sector                                           object
year                                              int64
company_id                                        int64
dtype: object

Data row sample and full columns:

,income_id,fiscal_date_ending,gross_profit,total_revenue,cost_of_revenue,costof_goods_and_services_sold,operating_income,selling_general_and_administrative,research_and_development,operating_expenses,investment_income_net,net_interest_income,interest_income,interest_expense,non_interest_income,other_non_operating_income,depreciation,depreciation_and_amortization,income_before_tax,income_tax_expense,interest_and_debt_expense,net_income_from_continuing_operations,comprehensive_income_net_of_tax,ebit,ebitda,net_income,symbol,sector,year,company_id
21,21,2019-12-31,3530000000,11510000000,7980000000,3819000000,3009000000,2788000000,0,4161000000,1000000,-677000000,22000000,677000000,11160000000,-8000000,207000000,1347000000,2150000000,81000000,705000000,2213000000,2062000000,2827000000,4174000000,2069000000,WBD,Comunicacion,2019,3
313,313,2021-01-31,10396000000,16675000000,6279000000,6279000000,4532000000,1940000000,3924000000,5864000000,57000000,-184000000,57000000,184000000,16675000000,4000000,486000000,1098000000,4409000000,77000000,184000000,4332000000,4350000000,4593000000,5691000000,4332000000,NVDA,Tecnologia de la Informacion,2021,52
187,187,2021-12-31,4103600000,9356900000,5253300000,2585300000,3132000000,811600000,0,3089400000,0,-870900000,1388400000,870900000,1236900000,566100000,1036200000,1346800000,2829500000,261800000,909100000,2567600000,1588200000,3132000000,5047200000,2567700000,AMT,Inmobiliario,2021,31
117,117,2019-12-31,16316218000,17380000000,1063755000,5595799000,3699000000,489397000,0,1080023000,26026000,-185129000,-129000,185000000,2000000,31000000,0,13000000,3545000000,810000000,185129000,2734910000,2731349000,3730000000,3743000000,2735000000,EOG,Energia,2019,19
70,70,2018-12-31,4042000000,21461000000,17419000000,85272000,-388000000,2835000000,1460000000,4430000000,24533000,-663071000,-71000,663000000,22184879000,22000000,1110000000,66000000,-918000000,58000000,663071000,-1062582000,-1018000000,-255000000,-189000000,-976000000,TSLA,Consumo Discrecional,2018,11

In [229]:
income_df.to_csv('4_income.csv', index=False)

In [215]:
stocks_df = pd.read_csv("market_values_since_2018_comas.csv", sep=';')

In [217]:
open_data(stocks_df)

Data shape is (96359, 12).

market_id      int64
date          object
symbol        object
open          object
high          object
low           object
close         object
volume         int64
company_id     int64
sector        object
shares         int64
market_cap     int64
dtype: object

Data row sample and full columns:

,market_id,date,symbol,open,high,low,close,volume,company_id,sector,shares,market_cap
88821,88821,24/12/2018,NEE,"174,45","175,38","166,92","168,08",1657460,45,Servicios Publicos,514100000,86409928000
88435,88435,08/07/2020,NEE,"246,83","254,14","246,12","253,27",2408287,45,Servicios Publicos,514100000,130206107000
18075,18075,08/02/2022,AMZN,"3135,01","3235,85","3111,01","3228,27",3802018,10,Consumo Discrecional,525750000,1697262952500
82322,82322,31/10/2023,DIS,"80,69","81,67","80,33","81,59",8672234,2,Comunicacion,1810940000,147754594600
90127,90127,13/10/2020,DUK,"92,64","93,26","91,3","92,92",2544541,46,Servicios Publicos,772482000,71779027440

In [218]:
explore_data(stocks_df)

There are 0 duplicate rows. Also;

            NaN  NaN %  EmptySpaces
market_id     0    0.0            0
date          0    0.0            0
symbol        0    0.0            0
open          0    0.0            0
high          0    0.0            0
low           0    0.0            0
close         0    0.0            0
volume        0    0.0            0
company_id    0    0.0            0
sector        0    0.0            0
shares        0    0.0            0
market_cap    0    0.0            0

In [230]:
stocks_df['name'] = stocks_df['symbol'].map(symbol_to_name_map)
stocks_df

,market_id,date,symbol,open,high,low,close,volume,company_id,sector,shares,market_cap,name
0,0,29/12/2023,AAPL,"193,9","194,4","191,72","192,53",42672148,50,Tecnologia de la Informacion,15115800000,2910244974000,Apple Inc
1,1,28/12/2023,AAPL,"194,14","194,66","193,17","193,58",34049898,50,Tecnologia de la Informacion,15115800000,2926116564000,Apple Inc
2,2,27/12/2023,AAPL,"192,49","193,5","191,09","193,15",47899806,50,Tecnologia de la Informacion,15115800000,2919616770000,Apple Inc
3,3,26/12/2023,AAPL,"193,61","193,89","192,83","193,05",28919310,50,Tecnologia de la Informacion,15115800000,2918105190000,Apple Inc
4,4,22/12/2023,AAPL,"195,18","195,41","192,97","193,6",37149570,50,Tecnologia de la Informacion,15115800000,2926418880000,Apple Inc
...,...,...,...,...,...,...,...,...,...,...,...,...,...
96354,96354,09/01/2017,EXC,"36,09","36,17","35,25","35,27",4680781,49,Servicios Publicos,1004830000,35440354100,Exelon Corporation
96355,96355,06/01/2017,EXC,"35,39","36,21","35,32","36,08",6322944,49,Servicios Publicos,1004830000,36254266400,Exelon Corporation
96356,96356,05/01/2017,EXC,"35,5","35,65","35,26","35,5",5148930,49,Servicios Publicos,1004830000,35671465000,Exelon Corporation
96357,96357,04/01/2017,EXC,"35,34","35,78","35,26","35,49",6651754,49,Servicios Publicos,1004830000,35661416700,Exelon Corporation
96358,96358,03/01/2017,EXC,"35,67","35,69","34,91","35,19",7296274,49,Servicios Publicos,1004830000,35359967700,Exelon Corporation

In [ ]:
stocks_df.to_csv("5_stocks_comas.csv", index=False,decimal=',', sep=';')

In [1]:
stocks_df.to_csv("5_stocks_puntos.csv", index=False)

NameError: name 'stocks_df' is not defined